import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

function generateSlug(year: number, make: string, model: string, vehicleType: string, stockNumber: string): string {
  return `${year}-${make}-${model}-${vehicleType}-${stockNumber}`
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '')
}

async function main() {
  // Seed taxonomies
  const taxonomies = [
    // Vehicle Types
    { type: 'vehicleType', value: 'School Bus' },
    { type: 'vehicleType', value: 'Shuttle Bus' },
    { type: 'vehicleType', value: 'Van' },
    { type: 'vehicleType', value: 'Coach' },
    // Makes
    { type: 'make', value: 'Blue Bird' },
    { type: 'make', value: 'Collins' },
    { type: 'make', value: 'ElDorado' },
    { type: 'make', value: 'Ford' },
    { type: 'make', value: 'Forest River' },
    { type: 'make', value: 'Freightliner' },
    { type: 'make', value: 'IC Bus' },
    { type: 'make', value: 'Thomas Built' },
    { type: 'make', value: 'Starcraft' },
    { type: 'make', value: 'Champion' },
    // Locations
    { type: 'location', value: 'Indianapolis, IN' },
    { type: 'location', value: 'Chicago, IL' },
    { type: 'location', value: 'Columbus, OH' },
    { type: 'location', value: 'Louisville, KY' },
    // Industries
    { type: 'industry', value: 'Senior Living' },
    { type: 'industry', value: 'Athletics' },
    { type: 'industry', value: 'Hospitality' },
    { type: 'industry', value: 'Prison Transport' },
    { type: 'industry', value: 'Childcare' },
    { type: 'industry', value: 'Churches' },
    { type: 'industry', value: 'Tour & Charter' },
    { type: 'industry', value: 'School District' },
    { type: 'industry', value: 'Corporate' },
  ]

  for (const tax of taxonomies) {
    await prisma.taxonomy.upsert({
      where: { type_value: { type: tax.type, value: tax.value } },
      update: {},
      create: tax,
    })
  }

  // Seed sample vehicles
  const vehicles = [
    {
      year: 2026,
      make: 'Forest River',
      model: 'ADA Van',
      vehicleType: 'Van',
      condition: 'New',
      stockNumber: '129055',
      vin: '1FDEE3FS1RDA29055',
      price: 89500,
      description: 'Brand new 2026 Forest River ADA Van with wheelchair accessibility features. Perfect for senior living communities and healthcare facilities. Equipped with a Braun lift system and modern amenities.',
      cdlRequired: 'Not Required',
      maxCapacity: 14,
      standardPassengers: 10,
      crew: 'Driver',
      wheelchairAccessible: 'Yes',
      liftManufacturer: 'Braun',
      wheelchairPositions: 4,
      fuelType: 'Gas',
      fuelTankCapacity: '55 gal',
      ac: '35,000 BTU',
      exteriorColor: 'White',
      interiorColor: 'Gray',
      brake: 'Hydraulic Disc',
      transmissionMfr: 'Ford',
      transmissionModel: '10-Speed Automatic',
      status: 'Published',
      includeOnWebsite: true,
      locations: JSON.stringify(['Indianapolis, IN']),
      industries: JSON.stringify(['Senior Living', 'Childcare']),
      images: JSON.stringify([
        '/images/sample/van-1.jpg',
        '/images/sample/van-2.jpg',
        '/images/sample/van-3.jpg',
      ]),
    },
    {
      year: 2025,
      make: 'Blue Bird',
      model: 'Vision',
      vehicleType: 'School Bus',
      condition: 'New',
      stockNumber: '128900',
      vin: '1BAKBCEA5RF123456',
      price: 125000,
      description: 'The Blue Bird Vision is the industry-leading Type C school bus featuring a front-engine design with exceptional maneuverability. This unit includes advanced safety features and comfortable seating for up to 72 passengers.',
      cdlRequired: 'Required',
      maxCapacity: 72,
      standardPassengers: 72,
      crew: 'Driver',
      wheelchairAccessible: 'No',
      fuelType: 'Diesel',
      fuelTankCapacity: '60 gal',
      ac: '65,000 BTU',
      exteriorColor: 'School Bus Yellow',
      interiorColor: 'Gray',
      engineMake: 'Cummins',
      engineModel: 'B6.7',
      brake: 'Air Disc',
      transmissionMfr: 'Allison',
      transmissionModel: '2500 Series',
      suspensionType: 'Leaf Spring',
      status: 'Published',
      includeOnWebsite: true,
      locations: JSON.stringify(['Indianapolis, IN', 'Chicago, IL']),
      industries: JSON.stringify(['School District']),
      images: JSON.stringify([
        '/images/sample/school-bus-1.jpg',
        '/images/sample/school-bus-2.jpg',
      ]),
    },
    {
      year: 2025,
      make: 'ElDorado',
      model: 'Advantage',
      vehicleType: 'Shuttle Bus',
      condition: 'New',
      stockNumber: '129100',
      vin: '1GBE4V1928F100001',
      price: 98750,
      description: 'The ElDorado Advantage shuttle bus offers premium comfort for mid-size passenger transport. Ideal for hotel shuttles, corporate campuses, and tour operators. Features include low-floor entry and generous luggage space.',
      cdlRequired: 'Not Required',
      maxCapacity: 25,
      standardPassengers: 22,
      crew: 'Driver + Co-Pilot',
      wheelchairAccessible: 'Yes',
      liftManufacturer: 'Ricon',
      wheelchairPositions: 2,
      fuelType: 'Diesel',
      fuelTankCapacity: '50 gal',
      ac: '45,000 BTU',
      exteriorColor: 'White',
      interiorColor: 'Blue',
      luggage: 'Rear Luggage Compartment',
      brake: 'Hydraulic Disc',
      transmissionMfr: 'Allison',
      transmissionModel: '1000 Series',
      wheelbase: '220"',
      suspensionType: 'Air Ride',
      status: 'Published',
      includeOnWebsite: true,
      locations: JSON.stringify(['Chicago, IL']),
      industries: JSON.stringify(['Hospitality', 'Corporate', 'Tour & Charter']),
      images: JSON.stringify([
        '/images/sample/shuttle-1.jpg',
        '/images/sample/shuttle-2.jpg',
        '/images/sample/shuttle-3.jpg',
      ]),
    },
    {
      year: 2024,
      make: 'Freightliner',
      model: 'S2C',
      vehicleType: 'Coach',
      condition: 'Pre-Owned',
      stockNumber: '128500',
      vin: '4UZABRDT5RCLU5678',
      price: 175000,
      mileage: 42000,
      description: 'Pre-owned Freightliner S2C coach in excellent condition. Previously used for charter service with meticulous maintenance records. Features reclining seats, overhead luggage bins, and entertainment system.',
      cdlRequired: 'Required',
      maxCapacity: 44,
      standardPassengers: 44,
      crew: 'Driver',
      wheelchairAccessible: 'No',
      fuelType: 'Diesel',
      fuelTankCapacity: '100 gal',
      ac: '120,000 BTU',
      exteriorColor: 'Silver',
      interiorColor: 'Black Leather',
      luggage: 'Under-floor Luggage Bays',
      brake: 'Air Disc',
      transmissionMfr: 'Allison',
      transmissionModel: 'B500',
      engineMake: 'Cummins',
      engineModel: 'L9',
      wheelbase: '315"',
      suspensionType: 'Air Ride',
      status: 'Published',
      includeOnWebsite: true,
      locations: JSON.stringify(['Columbus, OH']),
      industries: JSON.stringify(['Tour & Charter', 'Athletics']),
      images: JSON.stringify([
        '/images/sample/coach-1.jpg',
        '/images/sample/coach-2.jpg',
      ]),
    },
    {
      year: 2026,
      make: 'Collins',
      model: 'DH-XV',
      vehicleType: 'Shuttle Bus',
      condition: 'New',
      stockNumber: '129200',
      vin: '1GBE5V1F2RF200001',
      price: 82000,
      description: 'New Collins DH-XV shuttle bus designed for daily passenger transport. Compact design with a wide center aisle and durable commercial-grade interior. Excellent for church groups, daycares, and senior living facilities.',
      cdlRequired: 'Not Required',
      maxCapacity: 18,
      standardPassengers: 14,
      crew: 'Driver',
      wheelchairAccessible: 'Yes',
      liftManufacturer: 'Braun',
      wheelchairPositions: 3,
      fuelType: 'Gas',
      fuelTankCapacity: '40 gal',
      ac: '30,000 BTU',
      exteriorColor: 'White',
      interiorColor: 'Tan',
      brake: 'Hydraulic Disc',
      transmissionMfr: 'GM',
      transmissionModel: '6-Speed Automatic',
      wheelbase: '178"',
      status: 'Published',
      includeOnWebsite: true,
      locations: JSON.stringify(['Louisville, KY']),
      industries: JSON.stringify(['Churches', 'Senior Living', 'Childcare']),
      images: JSON.stringify([
        '/images/sample/shuttle-small-1.jpg',
      ]),
    },
    {
      year: 2023,
      make: 'Ford',
      model: 'Transit',
      vehicleType: 'Van',
      condition: 'Pre-Owned',
      stockNumber: '128300',
      vin: '1FTBW3XG5PKA12345',
      price: 45000,
      mileage: 28000,
      description: 'Pre-owned Ford Transit passenger van in great condition. Low mileage, well maintained. Perfect for small group transport needs.',
      cdlRequired: 'Not Required',
      maxCapacity: 15,
      standardPassengers: 14,
      crew: 'Driver',
      wheelchairAccessible: 'No',
      fuelType: 'Gas',
      fuelTankCapacity: '25 gal',
      ac: '20,000 BTU',
      exteriorColor: 'Blue',
      interiorColor: 'Gray',
      brake: 'Hydraulic Disc',
      transmissionMfr: 'Ford',
      transmissionModel: '10-Speed Automatic',
      status: 'Published',
      includeOnWebsite: true,
      locations: JSON.stringify(['Indianapolis, IN']),
      industries: JSON.stringify(['Corporate', 'Churches']),
      images: JSON.stringify([
        '/images/sample/transit-1.jpg',
      ]),
    },
    {
      year: 2025,
      make: 'IC Bus',
      model: 'CE Series',
      vehicleType: 'School Bus',
      condition: 'New',
      stockNumber: '129300',
      vin: '4DRBUC8N5RB300001',
      price: 115000,
      description: 'New IC Bus CE Series school bus with wheelchair accessibility. Features integrated child safety systems, GPS tracking pre-wired, and heavy-duty construction.',
      cdlRequired: 'Required',
      maxCapacity: 47,
      standardPassengers: 42,
      crew: 'Driver',
      wheelchairAccessible: 'Yes',
      liftManufacturer: 'Ricon',
      wheelchairPositions: 4,
      fuelType: 'Diesel',
      fuelTankCapacity: '60 gal',
      ac: '55,000 BTU',
      exteriorColor: 'School Bus Yellow',
      interiorColor: 'Gray',
      engineMake: 'Cummins',
      engineModel: 'B6.7',
      brake: 'Air Drum',
      transmissionMfr: 'Allison',
      transmissionModel: '2500 Series',
      wheelbase: '252"',
      suspensionType: 'Leaf Spring',
      status: 'Published',
      includeOnWebsite: true,
      locations: JSON.stringify(['Indianapolis, IN', 'Columbus, OH']),
      industries: JSON.stringify(['School District']),
      images: JSON.stringify([
        '/images/sample/ic-bus-1.jpg',
        '/images/sample/ic-bus-2.jpg',
      ]),
    },
    {
      year: 2026,
      make: 'Thomas Built',
      model: 'Saf-T-Liner EFX',
      vehicleType: 'School Bus',
      condition: 'New',
      stockNumber: '129400',
      vin: '1T7YU2E24RB400001',
      price: null,
      description: 'The Saf-T-Liner EFX is an all-electric school bus from Thomas Built Buses. Zero emissions, lower operating costs, and V2G capability. Ideal for forward-thinking school districts.',
      cdlRequired: 'Required',
      maxCapacity: 66,
      standardPassengers: 66,
      crew: 'Driver',
      wheelchairAccessible: 'No',
      fuelType: 'Electric',
      ac: '50,000 BTU',
      exteriorColor: 'School Bus Yellow',
      interiorColor: 'Blue',
      engineMake: 'Proterra',
      engineModel: 'E-Powertrain',
      brake: 'Regenerative + Air Disc',
      suspensionType: 'Air Ride',
      status: 'Published',
      includeOnWebsite: true,
      locations: JSON.stringify(['Chicago, IL']),
      industries: JSON.stringify(['School District']),
      images: JSON.stringify([
        '/images/sample/electric-bus-1.jpg',
      ]),
    },
    {
      year: 2024,
      make: 'Starcraft',
      model: 'Allstar XL',
      vehicleType: 'Shuttle Bus',
      condition: 'New',
      stockNumber: '129500',
      vin: '1HA6GKCL5RN500001',
      price: 78500,
      description: 'Starcraft Allstar XL shuttle bus with flexible seating configuration. Durable construction ideal for high-frequency routes in senior living, hotel, and corporate settings.',
      cdlRequired: 'Not Required',
      maxCapacity: 20,
      standardPassengers: 18,
      crew: 'Driver',
      wheelchairAccessible: 'Yes',
      liftManufacturer: 'Braun',
      wheelchairPositions: 2,
      fuelType: 'Gas',
      fuelTankCapacity: '45 gal',
      ac: '35,000 BTU',
      exteriorColor: 'White',
      interiorColor: 'Gray',
      brake: 'Hydraulic Disc',
      transmissionMfr: 'GM',
      transmissionModel: '6-Speed Automatic',
      wheelbase: '190"',
      suspensionType: 'Leaf Spring',
      status: 'Published',
      includeOnWebsite: true,
      locations: JSON.stringify(['Louisville, KY', 'Indianapolis, IN']),
      industries: JSON.stringify(['Senior Living', 'Hospitality', 'Corporate']),
      images: JSON.stringify([
        '/images/sample/starcraft-1.jpg',
        '/images/sample/starcraft-2.jpg',
      ]),
    },
    {
      year: 2025,
      make: 'Champion',
      model: 'Challenger',
      vehicleType: 'Coach',
      condition: 'New',
      stockNumber: '129600',
      vin: '1C9GKMFE6RF600001',
      price: 210000,
      description: 'The Champion Challenger coach offers luxury group transport with plush reclining seats, individual reading lights, USB charging at every seat, and a premium audio/video entertainment system.',
      cdlRequired: 'Required',
      maxCapacity: 38,
      standardPassengers: 38,
      crew: 'Driver + Co-Pilot',
      wheelchairAccessible: 'No',
      fuelType: 'Diesel',
      fuelTankCapacity: '90 gal',
      ac: '100,000 BTU',
      exteriorColor: 'Black',
      interiorColor: 'Tan Leather',
      luggage: 'Under-floor Luggage Bays + Overhead Bins',
      brake: 'Air Disc',
      transmissionMfr: 'Allison',
      transmissionModel: 'B500',
      engineMake: 'Cummins',
      engineModel: 'L9',
      wheelbase: '295"',
      suspensionType: 'Air Ride',
      status: 'Published',
      includeOnWebsite: true,
      locations: JSON.stringify(['Columbus, OH', 'Chicago, IL']),
      industries: JSON.stringify(['Tour & Charter', 'Athletics', 'Corporate']),
      images: JSON.stringify([
        '/images/sample/champion-1.jpg',
        '/images/sample/champion-2.jpg',
        '/images/sample/champion-3.jpg',
      ]),
    },
    {
      year: 2024,
      make: 'ElDorado',
      model: 'National',
      vehicleType: 'Van',
      condition: 'Pre-Owned',
      stockNumber: '128200',
      vin: '1GBE3FK7RF700001',
      mileage: 15000,
      price: 62000,
      description: 'Low mileage pre-owned ElDorado National van. Previously operated as a medical transport vehicle with excellent service history.',
      cdlRequired: 'Not Required',
      maxCapacity: 12,
      standardPassengers: 8,
      crew: 'Driver',
      wheelchairAccessible: 'Yes',
      liftManufacturer: 'Braun',
      wheelchairPositions: 3,
      fuelType: 'Gas',
      fuelTankCapacity: '35 gal',
      ac: '28,000 BTU',
      exteriorColor: 'White',
      interiorColor: 'Gray',
      brake: 'Hydraulic Disc',
      transmissionMfr: 'GM',
      transmissionModel: '6-Speed Automatic',
      wheelbase: '159"',
      status: 'Published',
      includeOnWebsite: true,
      locations: JSON.stringify(['Indianapolis, IN']),
      industries: JSON.stringify(['Senior Living', 'Childcare']),
      images: JSON.stringify([
        '/images/sample/eldorado-van-1.jpg',
      ]),
    },
    {
      year: 2025,
      make: 'Forest River',
      model: 'Berkshire',
      vehicleType: 'Shuttle Bus',
      condition: 'New',
      stockNumber: '129700',
      vin: '1FDFE4FS5RDA29700',
      price: 92000,
      description: 'New Forest River Berkshire shuttle bus — comfortable, reliable, and built for demanding commercial routes.',
      cdlRequired: 'Not Required',
      maxCapacity: 24,
      standardPassengers: 24,
      crew: 'Driver',
      wheelchairAccessible: 'No',
      fuelType: 'Diesel',
      fuelTankCapacity: '50 gal',
      ac: '40,000 BTU',
      exteriorColor: 'White',
      interiorColor: 'Blue',
      brake: 'Hydraulic Disc',
      transmissionMfr: 'Ford',
      transmissionModel: '6-Speed Automatic',
      wheelbase: '208"',
      suspensionType: 'Leaf Spring',
      status: 'Published',
      includeOnWebsite: true,
      locations: JSON.stringify(['Chicago, IL', 'Louisville, KY']),
      industries: JSON.stringify(['Hospitality', 'Corporate']),
      images: JSON.stringify([
        '/images/sample/berkshire-1.jpg',
      ]),
    },
    // Additional vehicles for better category coverage
    {
      year: 2024,
      make: 'Blue Bird',
      model: 'All American',
      vehicleType: 'School Bus',
      condition: 'New',
      stockNumber: '129800',
      vin: '1BAKBCEA8RF800001',
      price: 135000,
      description: 'The Blue Bird All American is a Type D, rear-engine, transit-style school bus with the largest capacity in the fleet. Ideal for large school districts needing maximum seating.',
      cdlRequired: 'Required',
      maxCapacity: 84,
      standardPassengers: 84,
      crew: 'Driver',
      wheelchairAccessible: 'No',
      fuelType: 'Diesel',
      fuelTankCapacity: '75 gal',
      ac: '75,000 BTU',
      exteriorColor: 'School Bus Yellow',
      interiorColor: 'Gray',
      engineMake: 'Cummins',
      engineModel: 'B6.7',
      brake: 'Air Disc',
      transmissionMfr: 'Allison',
      transmissionModel: '3000 Series',
      wheelbase: '280"',
      suspensionType: 'Air Ride',
      status: 'Published',
      includeOnWebsite: true,
      locations: JSON.stringify(['Indianapolis, IN', 'Columbus, OH']),
      industries: JSON.stringify(['School District']),
      images: JSON.stringify(['/images/sample/all-american-1.jpg']),
    },
    {
      year: 2023,
      make: 'Thomas Built',
      model: 'Saf-T-Liner C2',
      vehicleType: 'School Bus',
      condition: 'Pre-Owned',
      stockNumber: '128100',
      vin: '1T7YU2E20PB100001',
      price: 78000,
      mileage: 35000,
      description: 'Pre-owned Thomas Built Saf-T-Liner C2 with low mileage. Excellent condition with full service history. Great entry-level bus for growing districts.',
      cdlRequired: 'Required',
      maxCapacity: 65,
      standardPassengers: 65,
      crew: 'Driver',
      wheelchairAccessible: 'No',
      fuelType: 'Diesel',
      fuelTankCapacity: '60 gal',
      ac: '55,000 BTU',
      exteriorColor: 'School Bus Yellow',
      interiorColor: 'Gray',
      engineMake: 'Cummins',
      engineModel: 'B6.7',
      brake: 'Air Drum',
      transmissionMfr: 'Allison',
      transmissionModel: '2500 Series',
      suspensionType: 'Leaf Spring',
      status: 'Published',
      includeOnWebsite: true,
      locations: JSON.stringify(['Louisville, KY']),
      industries: JSON.stringify(['School District']),
      images: JSON.stringify(['/images/sample/c2-1.jpg']),
    },
    {
      year: 2026,
      make: 'IC Bus',
      model: 'RE Series',
      vehicleType: 'School Bus',
      condition: 'New',
      stockNumber: '129900',
      vin: '4DRBUC8N9RB900001',
      price: 142000,
      description: 'Brand new IC Bus RE Series rear-engine school bus with wheelchair lift. Maximum capacity and accessibility in one package.',
      cdlRequired: 'Required',
      maxCapacity: 78,
      standardPassengers: 72,
      crew: 'Driver',
      wheelchairAccessible: 'Yes',
      liftManufacturer: 'Ricon',
      wheelchairPositions: 4,
      fuelType: 'Diesel',
      fuelTankCapacity: '70 gal',
      ac: '70,000 BTU',
      exteriorColor: 'School Bus Yellow',
      interiorColor: 'Gray',
      engineMake: 'Cummins',
      engineModel: 'L9',
      brake: 'Air Disc',
      transmissionMfr: 'Allison',
      transmissionModel: '3000 Series',
      wheelbase: '295"',
      suspensionType: 'Air Ride',
      status: 'Published',
      includeOnWebsite: true,
      locations: JSON.stringify(['Chicago, IL', 'Indianapolis, IN']),
      industries: JSON.stringify(['School District']),
      images: JSON.stringify(['/images/sample/re-series-1.jpg']),
    },
    {
      year: 2025,
      make: 'Ford',
      model: 'E-Transit',
      vehicleType: 'Van',
      condition: 'New',
      stockNumber: '130000',
      vin: '1FTBW3XG7SKA00001',
      price: 72000,
      description: 'All-electric Ford E-Transit passenger van. Zero emissions with 126-mile range. Perfect for short-route corporate and campus shuttles.',
      cdlRequired: 'Not Required',
      maxCapacity: 12,
      standardPassengers: 12,
      crew: 'Driver',
      wheelchairAccessible: 'No',
      fuelType: 'Electric',
      ac: '18,000 BTU',
      exteriorColor: 'Oxford White',
      interiorColor: 'Dark Gray',
      brake: 'Regenerative + Disc',
      transmissionMfr: 'Ford',
      transmissionModel: 'Single-Speed Automatic',
      status: 'Published',
      includeOnWebsite: true,
      locations: JSON.stringify(['Indianapolis, IN']),
      industries: JSON.stringify(['Corporate', 'Hospitality']),
      images: JSON.stringify(['/images/sample/etransit-1.jpg']),
    },
    {
      year: 2024,
      make: 'Ford',
      model: 'Transit 350 HD',
      vehicleType: 'Van',
      condition: 'New',
      stockNumber: '130100',
      vin: '1FTBW3XG9RKA10001',
      price: 58000,
      description: 'Ford Transit 350 HD passenger van with extended body. High roof provides generous headroom. Ideal for airport transfers and group transport.',
      cdlRequired: 'Not Required',
      maxCapacity: 15,
      standardPassengers: 14,
      crew: 'Driver',
      wheelchairAccessible: 'No',
      fuelType: 'Gas',
      fuelTankCapacity: '25 gal',
      ac: '22,000 BTU',
      exteriorColor: 'Agate Black',
      interiorColor: 'Gray',
      brake: 'Hydraulic Disc',
      transmissionMfr: 'Ford',
      transmissionModel: '10-Speed Automatic',
      status: 'Published',
      includeOnWebsite: true,
      locations: JSON.stringify(['Columbus, OH', 'Chicago, IL']),
      industries: JSON.stringify(['Hospitality', 'Corporate', 'Churches']),
      images: JSON.stringify(['/images/sample/transit350-1.jpg']),
    },
    {
      year: 2023,
      make: 'Forest River',
      model: 'Starcraft ADA',
      vehicleType: 'Van',
      condition: 'Pre-Owned',
      stockNumber: '128050',
      vin: '1FDEE3FS3PDA05001',
      price: 52000,
      mileage: 22000,
      description: 'Pre-owned Forest River Starcraft ADA van with wheelchair ramp. Well-maintained with full service records. Great for medical transport and senior living.',
      cdlRequired: 'Not Required',
      maxCapacity: 10,
      standardPassengers: 6,
      crew: 'Driver',
      wheelchairAccessible: 'Yes',
      liftManufacturer: 'Braun',
      wheelchairPositions: 3,
      fuelType: 'Gas',
      fuelTankCapacity: '35 gal',
      ac: '25,000 BTU',
      exteriorColor: 'White',
      interiorColor: 'Gray',
      brake: 'Hydraulic Disc',
      transmissionMfr: 'Ford',
      transmissionModel: '10-Speed Automatic',
      wheelbase: '148"',
      status: 'Published',
      includeOnWebsite: true,
      locations: JSON.stringify(['Louisville, KY']),
      industries: JSON.stringify(['Senior Living', 'Childcare']),
      images: JSON.stringify(['/images/sample/starcraft-ada-1.jpg']),
    },
    {
      year: 2025,
      make: 'ElDorado',
      model: 'Aerotech 240',
      vehicleType: 'Shuttle Bus',
      condition: 'New',
      stockNumber: '130200',
      vin: '1GBE4V1958F200001',
      price: 105000,
      description: 'ElDorado Aerotech 240 medium-duty shuttle bus with rear luggage. Built on the Freightliner S2 chassis for durability and long service life.',
      cdlRequired: 'Required',
      maxCapacity: 30,
      standardPassengers: 28,
      crew: 'Driver + Co-Pilot',
      wheelchairAccessible: 'Yes',
      liftManufacturer: 'Ricon',
      wheelchairPositions: 2,
      fuelType: 'Diesel',
      fuelTankCapacity: '55 gal',
      ac: '50,000 BTU',
      exteriorColor: 'White',
      interiorColor: 'Gray',
      luggage: 'Rear Luggage Compartment',
      brake: 'Air Disc',
      transmissionMfr: 'Allison',
      transmissionModel: '2200 Series',
      wheelbase: '242"',
      suspensionType: 'Air Ride',
      status: 'Published',
      includeOnWebsite: true,
      locations: JSON.stringify(['Indianapolis, IN', 'Columbus, OH']),
      industries: JSON.stringify(['Hospitality', 'Tour & Charter', 'Corporate']),
      images: JSON.stringify(['/images/sample/aerotech-1.jpg']),
    },
    {
      year: 2024,
      make: 'Starcraft',
      model: 'eQuest XL',
      vehicleType: 'Shuttle Bus',
      condition: 'New',
      stockNumber: '130300',
      vin: '1HA6GKCL7RN300001',
      price: 115000,
      description: 'All-electric Starcraft eQuest XL shuttle bus. Zero-emission transit solution with 150-mile range. Ideal for campus loops and fixed-route services.',
      cdlRequired: 'Not Required',
      maxCapacity: 22,
      standardPassengers: 20,
      crew: 'Driver',
      wheelchairAccessible: 'Yes',
      liftManufacturer: 'Braun',
      wheelchairPositions: 2,
      fuelType: 'Electric',
      ac: '35,000 BTU',
      exteriorColor: 'Silver',
      interiorColor: 'Blue',
      brake: 'Regenerative + Hydraulic Disc',
      transmissionMfr: 'Dana',
      transmissionModel: 'TM4 Direct Drive',
      wheelbase: '195"',
      suspensionType: 'Air Ride',
      status: 'Published',
      includeOnWebsite: true,
      locations: JSON.stringify(['Chicago, IL']),
      industries: JSON.stringify(['Corporate', 'Hospitality', 'Senior Living']),
      images: JSON.stringify(['/images/sample/equest-1.jpg']),
    },
    {
      year: 2023,
      make: 'Collins',
      model: 'Low Floor',
      vehicleType: 'Shuttle Bus',
      condition: 'Pre-Owned',
      stockNumber: '128010',
      vin: '1GBE5V1F0PF010001',
      price: 65000,
      mileage: 38000,
      description: 'Pre-owned Collins Low Floor shuttle with kneeling feature for easy boarding. Previously used in senior living community with meticulous maintenance.',
      cdlRequired: 'Not Required',
      maxCapacity: 16,
      standardPassengers: 12,
      crew: 'Driver',
      wheelchairAccessible: 'Yes',
      liftManufacturer: 'Ricon',
      wheelchairPositions: 3,
      fuelType: 'Gas',
      fuelTankCapacity: '40 gal',
      ac: '28,000 BTU',
      exteriorColor: 'White',
      interiorColor: 'Tan',
      brake: 'Hydraulic Disc',
      transmissionMfr: 'GM',
      transmissionModel: '6-Speed Automatic',
      wheelbase: '172"',
      status: 'Published',
      includeOnWebsite: true,
      locations: JSON.stringify(['Louisville, KY', 'Indianapolis, IN']),
      industries: JSON.stringify(['Senior Living', 'Churches']),
      images: JSON.stringify(['/images/sample/collins-lowfloor-1.jpg']),
    },
    {
      year: 2025,
      make: 'Freightliner',
      model: 'M2 Coach',
      vehicleType: 'Coach',
      condition: 'New',
      stockNumber: '130400',
      vin: '4UZABRDT7RCL40001',
      price: 195000,
      description: 'New Freightliner M2-based coach with reclining seats, WiFi, and entertainment system. Built for long-haul charter and tour operations.',
      cdlRequired: 'Required',
      maxCapacity: 40,
      standardPassengers: 40,
      crew: 'Driver + Co-Pilot',
      wheelchairAccessible: 'No',
      fuelType: 'Diesel',
      fuelTankCapacity: '100 gal',
      ac: '110,000 BTU',
      exteriorColor: 'White',
      interiorColor: 'Black Leather',
      luggage: 'Under-floor Luggage Bays + Overhead Bins',
      brake: 'Air Disc',
      transmissionMfr: 'Allison',
      transmissionModel: 'B500',
      engineMake: 'Cummins',
      engineModel: 'L9',
      wheelbase: '310"',
      suspensionType: 'Air Ride',
      status: 'Published',
      includeOnWebsite: true,
      locations: JSON.stringify(['Columbus, OH']),
      industries: JSON.stringify(['Tour & Charter', 'Athletics']),
      images: JSON.stringify(['/images/sample/m2-coach-1.jpg']),
    },
    {
      year: 2024,
      make: 'Champion',
      model: 'Defender',
      vehicleType: 'Coach',
      condition: 'New',
      stockNumber: '130500',
      vin: '1C9GKMFE8RF500001',
      price: 185000,
      description: 'Champion Defender mid-size coach with ADA wheelchair lift. Versatile design for tour, charter, and accessible group transport.',
      cdlRequired: 'Required',
      maxCapacity: 33,
      standardPassengers: 29,
      crew: 'Driver + Co-Pilot',
      wheelchairAccessible: 'Yes',
      liftManufacturer: 'Ricon',
      wheelchairPositions: 2,
      fuelType: 'Diesel',
      fuelTankCapacity: '80 gal',
      ac: '90,000 BTU',
      exteriorColor: 'Midnight Blue',
      interiorColor: 'Gray Leather',
      luggage: 'Under-floor Luggage Bays',
      brake: 'Air Disc',
      transmissionMfr: 'Allison',
      transmissionModel: 'B400',
      engineMake: 'Cummins',
      engineModel: 'B6.7',
      wheelbase: '275"',
      suspensionType: 'Air Ride',
      status: 'Published',
      includeOnWebsite: true,
      locations: JSON.stringify(['Chicago, IL', 'Indianapolis, IN']),
      industries: JSON.stringify(['Tour & Charter', 'Athletics', 'Corporate']),
      images: JSON.stringify(['/images/sample/defender-1.jpg']),
    },
    {
      year: 2022,
      make: 'Freightliner',
      model: 'S2C Executive',
      vehicleType: 'Coach',
      condition: 'Pre-Owned',
      stockNumber: '127900',
      vin: '4UZABRDT3NCL79001',
      price: 155000,
      mileage: 58000,
      description: 'Pre-owned Freightliner S2C Executive coach. Well-maintained charter vehicle with premium leather seating and entertainment system. Excellent value for tour operators.',
      cdlRequired: 'Required',
      maxCapacity: 42,
      standardPassengers: 42,
      crew: 'Driver',
      wheelchairAccessible: 'No',
      fuelType: 'Diesel',
      fuelTankCapacity: '100 gal',
      ac: '120,000 BTU',
      exteriorColor: 'Charcoal',
      interiorColor: 'Burgundy Leather',
      luggage: 'Under-floor Luggage Bays + Overhead Bins',
      brake: 'Air Disc',
      transmissionMfr: 'Allison',
      transmissionModel: 'B500',
      engineMake: 'Cummins',
      engineModel: 'L9',
      wheelbase: '315"',
      suspensionType: 'Air Ride',
      status: 'Published',
      includeOnWebsite: true,
      locations: JSON.stringify(['Louisville, KY', 'Columbus, OH']),
      industries: JSON.stringify(['Tour & Charter', 'Athletics', 'Corporate']),
      images: JSON.stringify(['/images/sample/s2c-exec-1.jpg']),
    },
    {
      year: 2026,
      make: 'Ford',
      model: 'Transit AWD',
      vehicleType: 'Van',
      condition: 'New',
      stockNumber: '130600',
      vin: '1FTBW3XG1TKA60001',
      price: 65000,
      description: 'New Ford Transit AWD passenger van with all-wheel drive for year-round reliability. High-roof model with 15-passenger seating.',
      cdlRequired: 'Not Required',
      maxCapacity: 15,
      standardPassengers: 14,
      crew: 'Driver',
      wheelchairAccessible: 'No',
      fuelType: 'Gas',
      fuelTankCapacity: '25 gal',
      ac: '22,000 BTU',
      exteriorColor: 'Iconic Silver',
      interiorColor: 'Dark Gray',
      brake: 'Hydraulic Disc',
      transmissionMfr: 'Ford',
      transmissionModel: '10-Speed Automatic',
      status: 'Published',
      includeOnWebsite: true,
      locations: JSON.stringify(['Chicago, IL', 'Columbus, OH']),
      industries: JSON.stringify(['Churches', 'Corporate']),
      images: JSON.stringify(['/images/sample/transit-awd-1.jpg']),
    },
    {
      year: 2025,
      make: 'ElDorado',
      model: 'Passport',
      vehicleType: 'Van',
      condition: 'New',
      stockNumber: '130700',
      vin: '1GBE3FK9SRF700001',
      price: 69500,
      description: 'New ElDorado Passport ADA-accessible van built on the GM chassis. Features a side-entry wheelchair ramp and flexible seating layouts.',
      cdlRequired: 'Not Required',
      maxCapacity: 11,
      standardPassengers: 7,
      crew: 'Driver',
      wheelchairAccessible: 'Yes',
      liftManufacturer: 'Braun',
      wheelchairPositions: 3,
      fuelType: 'Gas',
      fuelTankCapacity: '36 gal',
      ac: '26,000 BTU',
      exteriorColor: 'White',
      interiorColor: 'Gray',
      brake: 'Hydraulic Disc',
      transmissionMfr: 'GM',
      transmissionModel: '6-Speed Automatic',
      wheelbase: '159"',
      status: 'Published',
      includeOnWebsite: true,
      locations: JSON.stringify(['Indianapolis, IN', 'Louisville, KY']),
      industries: JSON.stringify(['Senior Living', 'Childcare', 'Prison Transport']),
      images: JSON.stringify(['/images/sample/passport-1.jpg']),
    },
    {
      year: 2024,
      make: 'Collins',
      model: 'Multi-Function',
      vehicleType: 'Shuttle Bus',
      condition: 'New',
      stockNumber: '130800',
      vin: '1GBE5V1F4RF800001',
      price: 88000,
      description: 'Collins Multi-Function shuttle bus with removable seating. Converts between passenger and cargo configurations. Ideal for multi-use fleet operations.',
      cdlRequired: 'Not Required',
      maxCapacity: 20,
      standardPassengers: 16,
      crew: 'Driver',
      wheelchairAccessible: 'Yes',
      liftManufacturer: 'Braun',
      wheelchairPositions: 2,
      fuelType: 'Gas',
      fuelTankCapacity: '43 gal',
      ac: '32,000 BTU',
      exteriorColor: 'White',
      interiorColor: 'Gray',
      brake: 'Hydraulic Disc',
      transmissionMfr: 'GM',
      transmissionModel: '6-Speed Automatic',
      wheelbase: '182"',
      suspensionType: 'Leaf Spring',
      status: 'Published',
      includeOnWebsite: true,
      locations: JSON.stringify(['Columbus, OH', 'Chicago, IL']),
      industries: JSON.stringify(['Churches', 'Senior Living', 'Hospitality']),
      images: JSON.stringify(['/images/sample/collins-mf-1.jpg']),
    },
    {
      year: 2023,
      make: 'Blue Bird',
      model: 'Micro Bird G5',
      vehicleType: 'School Bus',
      condition: 'Pre-Owned',
      stockNumber: '127800',
      vin: '1BAKBCEA1PF780001',
      price: 55000,
      mileage: 41000,
      description: 'Pre-owned Blue Bird Micro Bird G5 Type A school bus. Compact design perfect for small routes and tight neighborhoods. Well-maintained fleet vehicle.',
      cdlRequired: 'Not Required',
      maxCapacity: 24,
      standardPassengers: 24,
      crew: 'Driver',
      wheelchairAccessible: 'No',
      fuelType: 'Gas',
      fuelTankCapacity: '35 gal',
      ac: '28,000 BTU',
      exteriorColor: 'School Bus Yellow',
      interiorColor: 'Gray',
      engineMake: 'GM',
      engineModel: '6.6L V8',
      brake: 'Hydraulic Disc',
      transmissionMfr: 'GM',
      transmissionModel: '6-Speed Automatic',
      wheelbase: '168"',
      suspensionType: 'Leaf Spring',
      status: 'Published',
      includeOnWebsite: true,
      locations: JSON.stringify(['Indianapolis, IN']),
      industries: JSON.stringify(['School District', 'Childcare']),
      images: JSON.stringify(['/images/sample/microbird-1.jpg']),
    },
    {
      year: 2026,
      make: 'Blue Bird',
      model: 'Electric Vision',
      vehicleType: 'School Bus',
      condition: 'New',
      stockNumber: '131000',
      vin: '1BAKBCEA3TF100001',
      price: null,
      description: 'All-electric Blue Bird Vision school bus. Zero emissions, vehicle-to-grid (V2G) capability, and dramatically lower operating costs. Eligible for EPA Clean School Bus rebates.',
      cdlRequired: 'Required',
      maxCapacity: 72,
      standardPassengers: 72,
      crew: 'Driver',
      wheelchairAccessible: 'No',
      fuelType: 'Electric',
      ac: '55,000 BTU',
      exteriorColor: 'School Bus Yellow',
      interiorColor: 'Blue',
      engineMake: 'Blue Bird',
      engineModel: 'EV Drivetrain',
      brake: 'Regenerative + Air Disc',
      suspensionType: 'Air Ride',
      status: 'Published',
      includeOnWebsite: true,
      locations: JSON.stringify(['Chicago, IL', 'Columbus, OH']),
      industries: JSON.stringify(['School District']),
      images: JSON.stringify(['/images/sample/bb-electric-1.jpg']),
    },
    {
      year: 2024,
      make: 'Starcraft',
      model: 'MVP',
      vehicleType: 'Van',
      condition: 'New',
      stockNumber: '130900',
      vin: '1HA6GKCL5RN900001',
      price: 54000,
      description: 'Starcraft MVP passenger van with commercial-grade interior. Easy-clean flooring and grab handles throughout. Popular choice for daycare and church groups.',
      cdlRequired: 'Not Required',
      maxCapacity: 14,
      standardPassengers: 12,
      crew: 'Driver',
      wheelchairAccessible: 'Yes',
      liftManufacturer: 'Braun',
      wheelchairPositions: 2,
      fuelType: 'Gas',
      fuelTankCapacity: '25 gal',
      ac: '20,000 BTU',
      exteriorColor: 'White',
      interiorColor: 'Gray',
      brake: 'Hydraulic Disc',
      transmissionMfr: 'Ford',
      transmissionModel: '10-Speed Automatic',
      wheelbase: '148"',
      status: 'Published',
      includeOnWebsite: true,
      locations: JSON.stringify(['Louisville, KY', 'Chicago, IL']),
      industries: JSON.stringify(['Childcare', 'Churches', 'Senior Living']),
      images: JSON.stringify(['/images/sample/mvp-1.jpg']),
    },
    {
      year: 2025,
      make: 'Champion',
      model: 'LF Transport',
      vehicleType: 'Coach',
      condition: 'New',
      stockNumber: '131100',
      vin: '1C9GKMFE2SF110001',
      price: 225000,
      description: 'Champion LF Transport luxury coach with low-floor entry. Premium amenities include leather seating, individual climate controls, and onboard restroom.',
      cdlRequired: 'Required',
      maxCapacity: 36,
      standardPassengers: 36,
      crew: 'Driver + Co-Pilot',
      wheelchairAccessible: 'Yes',
      liftManufacturer: 'Ricon',
      wheelchairPositions: 2,
      fuelType: 'Diesel',
      fuelTankCapacity: '95 gal',
      ac: '105,000 BTU',
      exteriorColor: 'Pearl White',
      interiorColor: 'Tan Leather',
      luggage: 'Under-floor Luggage Bays + Overhead Bins',
      brake: 'Air Disc',
      transmissionMfr: 'Allison',
      transmissionModel: 'B500',
      engineMake: 'Cummins',
      engineModel: 'L9',
      wheelbase: '300"',
      suspensionType: 'Air Ride',
      status: 'Published',
      includeOnWebsite: true,
      locations: JSON.stringify(['Indianapolis, IN', 'Louisville, KY']),
      industries: JSON.stringify(['Tour & Charter', 'Corporate', 'Athletics']),
      images: JSON.stringify(['/images/sample/lf-transport-1.jpg']),
    },
    {
      year: 2022,
      make: 'ElDorado',
      model: 'EZ Rider II',
      vehicleType: 'Shuttle Bus',
      condition: 'Pre-Owned',
      stockNumber: '127700',
      vin: '1GBE4V1920F770001',
      price: 72000,
      mileage: 52000,
      description: 'Pre-owned ElDorado EZ Rider II heavy-duty transit shuttle. Built for high-frequency urban routes with standing room and wide doors.',
      cdlRequired: 'Required',
      maxCapacity: 28,
      standardPassengers: 22,
      crew: 'Driver',
      wheelchairAccessible: 'Yes',
      liftManufacturer: 'Ricon',
      wheelchairPositions: 4,
      fuelType: 'Diesel',
      fuelTankCapacity: '55 gal',
      ac: '48,000 BTU',
      exteriorColor: 'White',
      interiorColor: 'Blue',
      brake: 'Air Disc',
      transmissionMfr: 'Allison',
      transmissionModel: '2200 Series',
      wheelbase: '235"',
      suspensionType: 'Air Ride',
      status: 'Published',
      includeOnWebsite: true,
      locations: JSON.stringify(['Columbus, OH', 'Louisville, KY']),
      industries: JSON.stringify(['Senior Living', 'Hospitality', 'Prison Transport']),
      images: JSON.stringify(['/images/sample/ezrider-1.jpg']),
    },
    {
      year: 2025,
      make: 'Forest River',
      model: 'Shuttle Plus',
      vehicleType: 'Shuttle Bus',
      condition: 'New',
      stockNumber: '131200',
      vin: '1FDFE4FS7SDA12001',
      price: 96000,
      description: 'Forest River Shuttle Plus with premium seating and overhead storage. Ford F-550 chassis with proven reliability for daily commercial service.',
      cdlRequired: 'Not Required',
      maxCapacity: 26,
      standardPassengers: 24,
      crew: 'Driver',
      wheelchairAccessible: 'No',
      fuelType: 'Diesel',
      fuelTankCapacity: '50 gal',
      ac: '42,000 BTU',
      exteriorColor: 'White',
      interiorColor: 'Charcoal',
      luggage: 'Rear Luggage Compartment',
      brake: 'Hydraulic Disc',
      transmissionMfr: 'Ford',
      transmissionModel: '10-Speed Automatic',
      wheelbase: '212"',
      suspensionType: 'Leaf Spring',
      status: 'Published',
      includeOnWebsite: true,
      locations: JSON.stringify(['Chicago, IL', 'Indianapolis, IN']),
      industries: JSON.stringify(['Hospitality', 'Corporate', 'Tour & Charter']),
      images: JSON.stringify(['/images/sample/shuttle-plus-1.jpg']),
    },
  ]

  for (const vehicle of vehicles) {
    const slug = generateSlug(vehicle.year, vehicle.make, vehicle.model, vehicle.vehicleType, vehicle.stockNumber)
    await prisma.vehicle.upsert({
      where: { stockNumber: vehicle.stockNumber },
      update: { ...vehicle, slug },
      create: { ...vehicle, slug, visibility: 'Public' },
    })
  }

  console.log('Seed completed: taxonomies and vehicles created.')
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
