import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

function generateSlug(year: number, make: string, model: string, vehicleType: string, stockNumber: string): string {
  return `${year}-${make}-${model}-${vehicleType}-${stockNumber}`
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '')
}

async function main() {
  // Seed taxonomies
  const taxonomies = [
    // Vehicle Types
    { type: 'vehicleType', value: 'School Bus' },
    { type: 'vehicleType', value: 'Shuttle Bus' },
    { type: 'vehicleType', value: 'Van' },
    { type: 'vehicleType', value: 'Coach' },
    // Makes
    { type: 'make', value: 'Blue Bird' },
    { type: 'make', value: 'Collins' },
    { type: 'make', value: 'ElDorado' },
    { type: 'make', value: 'Ford' },
    { type: 'make', value: 'Forest River' },
    { type: 'make', value: 'Freightliner' },
    { type: 'make', value: 'IC Bus' },
    { type: 'make', value: 'Thomas Built' },
    { type: 'make', value: 'Starcraft' },
    { type: 'make', value: 'Champion' },
    // Locations
    { type: 'location', value: 'Indianapolis, IN' },
    { type: 'location', value: 'Chicago, IL' },
    { type: 'location', value: 'Columbus, OH' },
    { type: 'location', value: 'Louisville, KY' },
    // Industries
    { type: 'industry', value: 'Senior Living' },
    { type: 'industry', value: 'Athletics' },
    { type: 'industry', value: 'Hospitality' },
    { type: 'industry', value: 'Prison Transport' },
    { type: 'industry', value: 'Childcare' },
    { type: 'industry', value: 'Churches' },
    { type: 'industry', value: 'Tour & Charter' },
    { type: 'industry', value: 'School District' },
    { type: 'industry', value: 'Corporate' },
  ]

  for (const tax of taxonomies) {
    await prisma.taxonomy.upsert({
      where: { type_value: { type: tax.type, value: tax.value } },
      update: {},
      create: tax,
    })
  }

  // Seed sample vehicles
  const vehicles = [
    {
      year: 2026,
      make: 'Forest River',
      model: 'ADA Van',
      vehicleType: 'Van',
      condition: 'New',
      stockNumber: '129055',
      vin: '1FDEE3FS1RDA29055',
      price: 89500,
      description: 'Brand new 2026 Forest River ADA Van with wheelchair accessibility features. Perfect for senior living communities and healthcare facilities. Equipped with a Braun lift system and modern amenities.',
      cdlRequired: 'Not Required',
      maxCapacity: 14,
      standardPassengers: 10,
      crew: 'Driver',
      wheelchairAccessible: 'Yes',
      liftManufacturer: 'Braun',
      wheelchairPositions: 4,
      fuelType: 'Gas',
      fuelTankCapacity: '55 gal',
      ac: '35,000 BTU',
      exteriorColor: 'White',
      interiorColor: 'Gray',
      brake: 'Hydraulic Disc',
      transmissionMfr: 'Ford',
      transmissionModel: '10-Speed Automatic',
      status: 'Published',
      includeOnWebsite: true,
      locations: JSON.stringify(['Indianapolis, IN']),
      industries: JSON.stringify(['Senior Living', 'Childcare']),
      images: JSON.stringify([
        '/images/sample/van-1.jpg',
        '/images/sample/van-2.jpg',
        '/images/sample/van-3.jpg',
      ]),
    },
    {
      year: 2025,
      make: 'Blue Bird',
      model: 'Vision',
      vehicleType: 'School Bus',
      condition: 'New',
      stockNumber: '128900',
      vin: '1BAKBCEA5RF123456',
      price: 125000,
      description: 'The Blue Bird Vision is the industry-leading Type C school bus featuring a front-engine design with exceptional maneuverability. This unit includes advanced safety features and comfortable seating for up to 72 passengers.',
      cdlRequired: 'Required',
      maxCapacity: 72,
      standardPassengers: 72,
      crew: 'Driver',
      wheelchairAccessible: 'No',
      fuelType: 'Diesel',
      fuelTankCapacity: '60 gal',
      ac: '65,000 BTU',
      exteriorColor: 'School Bus Yellow',
      interiorColor: 'Gray',
      engineMake: 'Cummins',
      engineModel: 'B6.7',
      brake: 'Air Disc',
      transmissionMfr: 'Allison',
      transmissionModel: '2500 Series',
      suspensionType: 'Leaf Spring',
      status: 'Published',
      includeOnWebsite: true,
      locations: JSON.stringify(['Indianapolis, IN', 'Chicago, IL']),
      industries: JSON.stringify(['School District']),
      images: JSON.stringify([
        '/images/sample/school-bus-1.jpg',
        '/images/sample/school-bus-2.jpg',
      ]),
    },
    {
      year: 2025,
      make: 'ElDorado',
      model: 'Advantage',
      vehicleType: 'Shuttle Bus',
      condition: 'New',
      stockNumber: '129100',
      vin: '1GBE4V1928F100001',
      price: 98750,
      description: 'The ElDorado Advantage shuttle bus offers premium comfort for mid-size passenger transport. Ideal for hotel shuttles, corporate campuses, and tour operators. Features include low-floor entry and generous luggage space.',
      cdlRequired: 'Not Required',
      maxCapacity: 25,
      standardPassengers: 22,
      crew: 'Driver + Co-Pilot',
      wheelchairAccessible: 'Yes',
      liftManufacturer: 'Ricon',
      wheelchairPositions: 2,
      fuelType: 'Diesel',
      fuelTankCapacity: '50 gal',
      ac: '45,000 BTU',
      exteriorColor: 'White',
      interiorColor: 'Blue',
      luggage: 'Rear Luggage Compartment',
      brake: 'Hydraulic Disc',
      transmissionMfr: 'Allison',
      transmissionModel: '1000 Series',
      wheelbase: '220"',
      suspensionType: 'Air Ride',
      status: 'Published',
      includeOnWebsite: true,
      locations: JSON.stringify(['Chicago, IL']),
      industries: JSON.stringify(['Hospitality', 'Corporate', 'Tour & Charter']),
      images: JSON.stringify([
        '/images/sample/shuttle-1.jpg',
        '/images/sample/shuttle-2.jpg',
        '/images/sample/shuttle-3.jpg',
      ]),
    },
    {
      year: 2024,
      make: 'Freightliner',
      model: 'S2C',
      vehicleType: 'Coach',
      condition: 'Pre-Owned',
      stockNumber: '128500',
      vin: '4UZABRDT5RCLU5678',
      price: 175000,
      mileage: 42000,
      description: 'Pre-owned Freightliner S2C coach in excellent condition. Previously used for charter service with meticulous maintenance records. Features reclining seats, overhead luggage bins, and entertainment system.',
      cdlRequired: 'Required',
      maxCapacity: 44,
      standardPassengers: 44,
      crew: 'Driver',
      wheelchairAccessible: 'No',
      fuelType: 'Diesel',
      fuelTankCapacity: '100 gal',
      ac: '120,000 BTU',
      exteriorColor: 'Silver',
      interiorColor: 'Black Leather',
      luggage: 'Under-floor Luggage Bays',
      brake: 'Air Disc',
      transmissionMfr: 'Allison',
      transmissionModel: 'B500',
      engineMake: 'Cummins',
      engineModel: 'L9',
      wheelbase: '315"',
      suspensionType: 'Air Ride',
      status: 'Published',
      includeOnWebsite: true,
      locations: JSON.stringify(['Columbus, OH']),
      industries: JSON.stringify(['Tour & Charter', 'Athletics']),
      images: JSON.stringify([
        '/images/sample/coach-1.jpg',
        '/images/sample/coach-2.jpg',
      ]),
    },
    {
      year: 2026,
      make: 'Collins',
      model: 'DH-XV',
      vehicleType: 'Shuttle Bus',
      condition: 'New',
      stockNumber: '129200',
      vin: '1GBE5V1F2RF200001',
      price: 82000,
      description: 'New Collins DH-XV shuttle bus designed for daily passenger transport. Compact design with a wide center aisle and durable commercial-grade interior. Excellent for church groups, daycares, and senior living facilities.',
      cdlRequired: 'Not Required',
      maxCapacity: 18,
      standardPassengers: 14,
      crew: 'Driver',
      wheelchairAccessible: 'Yes',
      liftManufacturer: 'Braun',
      wheelchairPositions: 3,
      fuelType: 'Gas',
      fuelTankCapacity: '40 gal',
      ac: '30,000 BTU',
      exteriorColor: 'White',
      interiorColor: 'Tan',
      brake: 'Hydraulic Disc',
      transmissionMfr: 'GM',
      transmissionModel: '6-Speed Automatic',
      wheelbase: '178"',
      status: 'Published',
      includeOnWebsite: true,
      locations: JSON.stringify(['Louisville, KY']),
      industries: JSON.stringify(['Churches', 'Senior Living', 'Childcare']),
      images: JSON.stringify([
        '/images/sample/shuttle-small-1.jpg',
      ]),
    },
    {
      year: 2023,
      make: 'Ford',
      model: 'Transit',
      vehicleType: 'Van',
      condition: 'Pre-Owned',
      stockNumber: '128300',
      vin: '1FTBW3XG5PKA12345',
      price: 45000,
      mileage: 28000,
      description: 'Pre-owned Ford Transit passenger van in great condition. Low mileage, well maintained. Perfect for small group transport needs.',
      cdlRequired: 'Not Required',
      maxCapacity: 15,
      standardPassengers: 14,
      crew: 'Driver',
      wheelchairAccessible: 'No',
      fuelType: 'Gas',
      fuelTankCapacity: '25 gal',
      ac: '20,000 BTU',
      exteriorColor: 'Blue',
      interiorColor: 'Gray',
      brake: 'Hydraulic Disc',
      transmissionMfr: 'Ford',
      transmissionModel: '10-Speed Automatic',
      status: 'Published',
      includeOnWebsite: true,
      locations: JSON.stringify(['Indianapolis, IN']),
      industries: JSON.stringify(['Corporate', 'Churches']),
      images: JSON.stringify([
        '/images/sample/transit-1.jpg',
      ]),
    },
    {
      year: 2025,
      make: 'IC Bus',
      model: 'CE Series',
      vehicleType: 'School Bus',
      condition: 'New',
      stockNumber: '129300',
      vin: '4DRBUC8N5RB300001',
      price: 115000,
      description: 'New IC Bus CE Series school bus with wheelchair accessibility. Features integrated child safety systems, GPS tracking pre-wired, and heavy-duty construction.',
      cdlRequired: 'Required',
      maxCapacity: 47,
      standardPassengers: 42,
      crew: 'Driver',
      wheelchairAccessible: 'Yes',
      liftManufacturer: 'Ricon',
      wheelchairPositions: 4,
      fuelType: 'Diesel',
      fuelTankCapacity: '60 gal',
      ac: '55,000 BTU',
      exteriorColor: 'School Bus Yellow',
      interiorColor: 'Gray',
      engineMake: 'Cummins',
      engineModel: 'B6.7',
      brake: 'Air Drum',
      transmissionMfr: 'Allison',
      transmissionModel: '2500 Series',
      wheelbase: '252"',
      suspensionType: 'Leaf Spring',
      status: 'Published',
      includeOnWebsite: true,
      locations: JSON.stringify(['Indianapolis, IN', 'Columbus, OH']),
      industries: JSON.stringify(['School District']),
      images: JSON.stringify([
        '/images/sample/ic-bus-1.jpg',
        '/images/sample/ic-bus-2.jpg',
      ]),
    },
    {
      year: 2026,
      make: 'Thomas Built',
      model: 'Saf-T-Liner EFX',
      vehicleType: 'School Bus',
      condition: 'New',
      stockNumber: '129400',
      vin: '1T7YU2E24RB400001',
      price: null,
      description: 'The Saf-T-Liner EFX is an all-electric school bus from Thomas Built Buses. Zero emissions, lower operating costs, and V2G capability. Ideal for forward-thinking school districts.',
      cdlRequired: 'Required',
      maxCapacity: 66,
      standardPassengers: 66,
      crew: 'Driver',
      wheelchairAccessible: 'No',
      fuelType: 'Electric',
      ac: '50,000 BTU',
      exteriorColor: 'School Bus Yellow',
      interiorColor: 'Blue',
      engineMake: 'Proterra',
      engineModel: 'E-Powertrain',
      brake: 'Regenerative + Air Disc',
      suspensionType: 'Air Ride',
      status: 'Published',
      includeOnWebsite: true,
      locations: JSON.stringify(['Chicago, IL']),
      industries: JSON.stringify(['School District']),
      images: JSON.stringify([
        '/images/sample/electric-bus-1.jpg',
      ]),
    },
    {
      year: 2024,
      make: 'Starcraft',
      model: 'Allstar XL',
      vehicleType: 'Shuttle Bus',
      condition: 'New',
      stockNumber: '129500',
      vin: '1HA6GKCL5RN500001',
      price: 78500,
      description: 'Starcraft Allstar XL shuttle bus with flexible seating configuration. Durable construction ideal for high-frequency routes in senior living, hotel, and corporate settings.',
      cdlRequired: 'Not Required',
      maxCapacity: 20,
      standardPassengers: 18,
      crew: 'Driver',
      wheelchairAccessible: 'Yes',
      liftManufacturer: 'Braun',
      wheelchairPositions: 2,
      fuelType: 'Gas',
      fuelTankCapacity: '45 gal',
      ac: '35,000 BTU',
      exteriorColor: 'White',
      interiorColor: 'Gray',
      brake: 'Hydraulic Disc',
      transmissionMfr: 'GM',
      transmissionModel: '6-Speed Automatic',
      wheelbase: '190"',
      suspensionType: 'Leaf Spring',
      status: 'Published',
      includeOnWebsite: true,
      locations: JSON.stringify(['Louisville, KY', 'Indianapolis, IN']),
      industries: JSON.stringify(['Senior Living', 'Hospitality', 'Corporate']),
      images: JSON.stringify([
        '/images/sample/starcraft-1.jpg',
        '/images/sample/starcraft-2.jpg',
      ]),
    },
    {
      year: 2025,
      make: 'Champion',
      model: 'Challenger',
      vehicleType: 'Coach',
      condition: 'New',
      stockNumber: '129600',
      vin: '1C9GKMFE6RF600001',
      price: 210000,
      description: 'The Champion Challenger coach offers luxury group transport with plush reclining seats, individual reading lights, USB charging at every seat, and a premium audio/video entertainment system.',
      cdlRequired: 'Required',
      maxCapacity: 38,
      standardPassengers: 38,
      crew: 'Driver + Co-Pilot',
      wheelchairAccessible: 'No',
      fuelType: 'Diesel',
      fuelTankCapacity: '90 gal',
      ac: '100,000 BTU',
      exteriorColor: 'Black',
      interiorColor: 'Tan Leather',
      luggage: 'Under-floor Luggage Bays + Overhead Bins',
      brake: 'Air Disc',
      transmissionMfr: 'Allison',
      transmissionModel: 'B500',
      engineMake: 'Cummins',
      engineModel: 'L9',
      wheelbase: '295"',
      suspensionType: 'Air Ride',
      status: 'Published',
      includeOnWebsite: true,
      locations: JSON.stringify(['Columbus, OH', 'Chicago, IL']),
      industries: JSON.stringify(['Tour & Charter', 'Athletics', 'Corporate']),
      images: JSON.stringify([
        '/images/sample/champion-1.jpg',
        '/images/sample/champion-2.jpg',
        '/images/sample/champion-3.jpg',
      ]),
    },
    {
      year: 2024,
      make: 'ElDorado',
      model: 'National',
      vehicleType: 'Van',
      condition: 'Pre-Owned',
      stockNumber: '128200',
      vin: '1GBE3FK7RF700001',
      mileage: 15000,
      price: 62000,
      description: 'Low mileage pre-owned ElDorado National van. Previously operated as a medical transport vehicle with excellent service history.',
      cdlRequired: 'Not Required',
      maxCapacity: 12,
      standardPassengers: 8,
      crew: 'Driver',
      wheelchairAccessible: 'Yes',
      liftManufacturer: 'Braun',
      wheelchairPositions: 3,
      fuelType: 'Gas',
      fuelTankCapacity: '35 gal',
      ac: '28,000 BTU',
      exteriorColor: 'White',
      interiorColor: 'Gray',
      brake: 'Hydraulic Disc',
      transmissionMfr: 'GM',
      transmissionModel: '6-Speed Automatic',
      wheelbase: '159"',
      status: 'Published',
      includeOnWebsite: true,
      locations: JSON.stringify(['Indianapolis, IN']),
      industries: JSON.stringify(['Senior Living', 'Childcare']),
      images: JSON.stringify([
        '/images/sample/eldorado-van-1.jpg',
      ]),
    },
    {
      year: 2025,
      make: 'Forest River',
      model: 'Berkshire',
      vehicleType: 'Shuttle Bus',
      condition: 'New',
      stockNumber: '129700',
      vin: '1FDFE4FS5RDA29700',
      price: 92000,
      description: 'New Forest River Berkshire shuttle bus — comfortable, reliable, and built for demanding commercial routes.',
      cdlRequired: 'Not Required',
      maxCapacity: 24,
      standardPassengers: 24,
      crew: 'Driver',
      wheelchairAccessible: 'No',
      fuelType: 'Diesel',
      fuelTankCapacity: '50 gal',
      ac: '40,000 BTU',
      exteriorColor: 'White',
      interiorColor: 'Blue',
      brake: 'Hydraulic Disc',
      transmissionMfr: 'Ford',
      transmissionModel: '6-Speed Automatic',
      wheelbase: '208"',
      suspensionType: 'Leaf Spring',
      status: 'Published',
      includeOnWebsite: true,
      locations: JSON.stringify(['Chicago, IL', 'Louisville, KY']),
      industries: JSON.stringify(['Hospitality', 'Corporate']),
      images: JSON.stringify([
        '/images/sample/berkshire-1.jpg',
      ]),
    },
  ]

  for (const vehicle of vehicles) {
    const slug = generateSlug(vehicle.year, vehicle.make, vehicle.model, vehicle.vehicleType, vehicle.stockNumber)
    await prisma.vehicle.upsert({
      where: { stockNumber: vehicle.stockNumber },
      update: { ...vehicle, slug },
      create: { ...vehicle, slug, visibility: 'Public' },
    })
  }

  console.log('Seed completed: taxonomies and vehicles created.')
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
